Repository OlhenShu/GreenCityMVPTemplate, pull requests merged in 2024-01, with the labels that each got.

#52 event feature
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/EventsController.java
  core/src/main/resources/application-dev.properties
  core/src/test/java/greencity/ModelUtils.java
  core/src/test/java/greencity/controller/EventControllerTest.java
  dao/src/main/java/greencity/entity/User.java
  dao/src/main/java/greencity/entity/event/Address.java
  dao/src/main/java/greencity/entity/event/Event.java
  dao/src/main/java/greencity/entity/event/EventDateLocation.java
  dao/src/main/java/greencity/entity/event/EventImages.java
  dao/src/main/java/greencity/repository/EventRepo.java
  dao/src/main/java/greencity/repository/UserRepo.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-coordinates-Proskurina.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-Osovskyi.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-dates-locations-Proskurina.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-image-Proskurina.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-images-Osovskyi.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-tags-Proskurina.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events-users-likes.Osovskyi.xml
  dao/src/main/resources/db/changelog/logs/ch-add-table-events_dates_locations-Osovskyi.xml
  service-api/src/main/java/greencity/constant/AppConstant.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/dto/event/AddEventDtoRequest.java
  service-api/src/main/java/greencity/dto/event/AddressDto.java
  service-api/src/main/java/greencity/dto/event/EventAuthorDto.java
  service-api/src/main/java/greencity/dto/event/EventDateLocationDto.java
  service-api/src/main/java/greencity/dto/event/EventDto.java
  service-api/src/main/java/greencity/dto/event/UpdateEventDto.java
  service-api/src/main/java/greencity/dto/geocoding/AddressDto.java
  service-api/src/main/java/greencity/dto/geocoding/AddressLatLngResponse.java
  service-api/src/main/java/greencity/dto/geocoding/AddressResponse.java
  service-api/src/main/java/greencity/dto/tag/TagUaEnDto.java
  service-api/src/main/java/greencity/service/EventService.java
  service-api/src/main/java/greencity/service/TagsService.java
  service/src/main/java/greencity/service/EventServiceImpl.java
  service/src/main/java/greencity/service/GoogleApiService.java
  service/src/main/java/greencity/service/TagsServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/service/EventServiceImplTest.java
  service/src/test/java/greencity/service/GoogleApiServiceTest.java
Labels: enhancement, event

#46 96 counter of user activities
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/EventsController.java
  core/src/test/java/greencity/controller/EventControllerTest.java
  dao/src/main/java/greencity/repository/EventRepo.java
  dao/src/main/java/greencity/repository/UserRepo.java
  dao/src/main/resources/db/changelog/logs/ch-delete-russian-translation-Klopov.xml
  service-api/src/main/java/greencity/service/EventService.java
  service/src/main/java/greencity/service/EventServiceImpl.java
  service/src/test/java/greencity/service/EventServiceImplTest.java
Labels: enhancement

#48 notification-feature implemented
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/FriendController.java
  core/src/main/java/greencity/controller/NotificationController.java
  core/src/test/java/greencity/controller/FriendControllerTest.java
  core/src/test/java/greencity/controller/NotificationControllerTest.java
  dao/src/main/java/greencity/entity/Notification.java
  dao/src/main/java/greencity/entity/NotifiedUser.java
  dao/src/main/java/greencity/enums/NotificationSource.java
  dao/src/main/java/greencity/enums/NotificationSourceType.java
  dao/src/main/java/greencity/repository/NotificationRepo.java
  dao/src/main/java/greencity/repository/NotifiedUserRepo.java
  dao/src/main/java/greencity/repository/UserRepo.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-change-notifications-add-column-notification-source-Kizerov.xml
  dao/src/main/resources/db/changelog/logs/ch-change-table-notification-and-add-table-notified-users-Kizerov.xml
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/dto/notification/NewNotificationDtoRequest.java
  service-api/src/main/java/greencity/dto/notification/NotificationDtoRequest.java
  service-api/src/main/java/greencity/dto/notification/NotificationDtoResponse.java
  service-api/src/main/java/greencity/dto/notification/NotificationsDto.java
  service-api/src/main/java/greencity/dto/notification/ShortNotificationDtoResponse.java
  service-api/src/main/java/greencity/enums/NotificationSourceType.java
  service-api/src/main/java/greencity/service/FriendService.java
  service-api/src/main/java/greencity/service/NotificationService.java
  service/src/main/java/greencity/mapping/NotificationDtoResponseMapper.java
  service/src/main/java/greencity/service/EcoNewsCommentServiceImpl.java
  service/src/main/java/greencity/service/EcoNewsServiceImpl.java
  service/src/main/java/greencity/service/FriendServiceImpl.java
  service/src/main/java/greencity/service/NotificationServiceImpl.java
  service/src/test/java/greencity/ModelUtils.java
  service/src/test/java/greencity/mapping/NotificationDtoResponseMapperTest.java
  service/src/test/java/greencity/service/EcoNewsCommentServiceImplTest.java
  service/src/test/java/greencity/service/EcoNewsServiceImplTest.java
  service/src/test/java/greencity/service/FriendServiceImplTest.java
  service/src/test/java/greencity/service/NotificationServiceImplTest.java
Labels: enhancement, notification

#50 add social network
  dao/src/main/java/greencity/entity/SocialNetwork.java
  dao/src/main/java/greencity/entity/User.java
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-change-table-social-networks-Malov.xml
Labels: enhancement

#26 244 - CategoryController.java
  core/src/main/java/greencity/controller/CategoryController.java
Labels: documentation
